from .data_utils import (
    drop_columns,
    encode_categorical,
    feature_target_split,
    handle_missing_values,
    load_data,
    normalize,
    shuffle_data_numpy,
    shuffle_data_pandas,
    split_data,
)
from .math_utils import add_bias_term, matrix_inverse, sigmoid
from .metrics import (
    accuracy,
    compute_roc_auc_score,
    confusion_matrix,
    explained_variance,
    f1_score,
    mean_absolute_error,
    mean_squared_error,
    median_absolute_error,
    precision_score,
    r2_score,
    recall_score,
    root_mean_squared_error,
)
from .training_utils import check_early_stopping, get_decayed_lr, log_progress
from .viz_utils import (
    plot_actual_vs_predicted,
    plot_confusion_matrix,
    plot_decision_boundary,
    plot_feature_importance,
    plot_learning_curve,
    plot_pairplot,
    plot_precision_recall_curve,
    plot_prediction_errors,
    plot_qq_residuals,
    plot_regression_line,
    plot_residual_histogram,
    plot_residuals_vs_predicted,
    plot_roc_curve,
    plot_scatter_for_classification,
    plot_scatter_for_regression,
    plot_two_decision_boundaries,
    plot_two_regression_lines,
)

__all__ = [
    # Data utilities
    "load_data",
    "split_data",
    "normalize",
    "handle_missing_values",
    "encode_categorical",
    "drop_columns",
    "feature_target_split",
    "shuffle_data_numpy",
    "shuffle_data_pandas",
    # Math utilities
    "add_bias_term",
    "matrix_inverse",
    "sigmoid",
    # Metrics
    "accuracy",
    "mean_squared_error",
    "root_mean_squared_error",
    "mean_absolute_error",
    "median_absolute_error",
    "r2_score",
    "explained_variance",
    "compute_roc_auc_score",
    "confusion_matrix",
    "precision_score",
    "recall_score",
    "f1_score",
    # Visualization utilities
    "plot_decision_boundary",
    "plot_learning_curve",
    "plot_two_decision_boundaries",
    "plot_regression_line",
    "plot_two_regression_lines",
    "plot_confusion_matrix",
    "plot_prediction_errors",
    "plot_feature_importance",
    "plot_actual_vs_predicted",
    "plot_residuals_vs_predicted",
    "plot_qq_residuals",
    "plot_residual_histogram",
    "plot_scatter_for_regression",
    "plot_roc_curve",
    "plot_precision_recall_curve",
    "plot_scatter_for_classification",
    "plot_pairplot",
    # Training utilities
    "check_early_stopping",
    "log_progress",
    "get_decayed_lr",
]
